### ISSUE TITLE
请问 sandbox 的使用场景在哪里？

### ISSUE THREAD

**Issue by heiheihoho1213** [ZxBing0066/z-sandbox#38]
是不是一定要和微前端结合才能发挥作用呢？这个库可否补充几个使用 demo？🤔

**Comment by ZxBing0066** [comment]
玩具罢了，就好像乾坤里的沙箱，不知要带来多少坑。

沙箱本质是为了数据隔离，然而js在同一个运行时无法做到完全的隔离，要为了安全就 iframe，为了方便就从规范下手。目前各种js沙箱只会徒增烦恼罢了。

**Comment by heiheihoho1213** [comment]
我也写了个sandbox，但是写完感觉除了微应用，其他地方用不到。感觉各种造轮子，造完了又不知道意义在哪里😂
